import { SweetAlertIcon } from "sweetalert2";
let success: SweetAlertIcon = 'success';
let error: SweetAlertIcon = 'error';
let warning: SweetAlertIcon = 'warning';
let info: SweetAlertIcon = 'info';
let question: SweetAlertIcon = 'question';
export const SweetAlertConstants = {
    noConexion: ' Revise su conexion de Internet.',
    noAccess: ' Su cuenta no tiene acceso a este Sistema.',
    SWEET_ALERT_TITLE_OK: 'Correcto...!',
    SWEET_ALERT_TITLE_MSG_OK: 'Operacion realizada correctamente...!',
    SWEET_ALERT_TITLE_DELETE: 'Eliminar',
    SWEET_ALERT_TITLE_MSG_DELETE: 'Esta Seguro de eliminar el elemento seleccionado?',
    SWEET_ALERT_TITLE_FAIL: 'Cuidado...!',
    SWEET_ALERT_TITLE_OPS: 'Ops! Ocurrio algo inesperado...',
    SWEET_ALERT_TITLE_ERROR: 'Error!',
    SWEET_ALERT_TITLE_OK_SAVE: 'Enviado correctamente',
    SWEET_ALERT_SUCCESS: success,
    SWEET_ALERT_ERROR: error,
    SWEET_ALERT_WARNING: warning,
    SWEET_ALERT_INFO: info,
    SWEET_ALERT_QUESTION: question,
    SWEET_ALERT_CONFIRM: 'Aceptar',
    SWEET_ALERT_CONFIRM_CLASS: 'mb-3 mr-5 btn btn-xs btn-primary',
    SWEET_ALERT_CANCEL: 'Cancelar',
    SWEET_ALERT_CANCEL_CLASS: 'mb-3 ml-5 btn btn-xs btn-danger',
    SWEET_ALERT_SHOW_CONFIRM_BUTTOM: true,
    SWEET_ALERT_SWEET: false,
    SWEET_ALERT_CLOSE: false,
    SWEET_ALERT_SHOW_CANCEL_BUTTOM: false,
    SWEET_ALERT_BUTTON_STYLIN: false,
    SWEET_ALERT_FOCUS_CONFIRM: false,
    SWEET_ALERT_FOCUS_CANCEL: true,
    SWEET_ALERT_POSITION_TOP: 'top',
    SWEET_ALERT_POSITION_TOP_START: 'top-start',
    SWEET_ALERT_POSITION_TOP_END: 'top-end',
    SWEET_ALERT_POSITION_CENTER: 'center',
    SWEET_ALERT_POSITION_CENTER_START: 'center-start',
    SWEET_ALERT_POSITION_CENTER_END: 'center-end',
    SWEET_ALERT_POSITION_BOTTOM: 'bottom',
    SWEET_ALERT_POSITION_BOTTOM_START: 'bottom-start',
    SWEET_ALERT_POSITION_BOTTOM_END: 'bottom-end',
    SWEET_ALERT_TIMER_1500: 1500,
    SWEET_ALERT_TIMER_2000: 2000,
    SWEET_ALERT_BG_DEFAULT: '',
    SWEET_ALERT_BG_DARK_OLIVE_GREEN: '#556B2F',
    SWEET_ALERT_BG_LAVNADER: '#E6E6FA',
    SWEET_ALERT_BG_GOLD: '#FFD700',
};